[Application]
dev_url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
sit_url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
uat_url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
browser=chromium
retry_count=2
wait=10
